spring:
    application:
        name: kdt-taskflow

    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
        username: ${DB_USERNAME:admin}
        password: ${DB_PASSWORD:112318}
        hikari:
            pool-name: project-pool
            maximum-pool-size: 10
    flyway:
        enabled: true
        baseline-on-migrate: true
        repair-on-migrate: true

    logging:
        level:
            com.kdt.taskflow.mapper: debug

server:
    port: 8080
    address: 0.0.0.0

mybatis:
    type-aliases-package: com.kdt.taskflow.domain
    type-handlers-package: com.kdt.taskflow.mapper.typehandler
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true

jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}